# Generated by Django 3.1.5 on 2021-06-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_de_referencia', models.CharField(max_length=75, verbose_name='ponto de referência')),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=200, verbose_name='endereço')),
                ('complemento', models.CharField(max_length=50)),
                ('ocupacao_maxima', models.IntegerField(verbose_name='ocupação máxima')),
                ('diaria', models.FloatField(verbose_name='diária')),
            ],
            options={
                'verbose_name': 'imóvel',
                'verbose_name_plural': 'imóveis',
            },
        ),
    ]
