# Generated by Django 3.1.5 on 2021-06-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='ponto_de_referencia',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='ponto de referência'),
        ),
    ]
