# Generated by Django 3.1.5 on 2021-06-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='fotos/default.jpg', upload_to='fotos/', verbose_name='foto')),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='imoveis.Foto'),
        ),
    ]
