# Generated by Django 3.1.5 on 2021-06-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_auto_20210618_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='nome',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
