# Generated by Django 3.1.5 on 2021-06-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_foto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='user',
        ),
    ]
