# Generated by Django 3.1.5 on 2021-06-18 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imoveis', '0006_remove_reserva_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='anfitriao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='anfitrião'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='hóspede'),
        ),
    ]
