# Generated by Django 3.1.5 on 2021-07-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_auto_20210630_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='index',
            field=models.IntegerField(blank=True, help_text='Utilizado para ordenar as fotos de um imóvel.', null=True, verbose_name='Índice'),
        ),
    ]
