# Generated by Django 3.1.5 on 2021-07-10 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_foto_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='fotos',
        ),
        migrations.AddField(
            model_name='foto',
            name='imovel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='imoveis.imovel', verbose_name='imóvel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foto',
            name='index',
            field=models.IntegerField(blank=True, help_text='Utilizado para ordenar as fotos de um imóvel.', null=True, verbose_name='índice'),
        ),
    ]
