# Generated by Django 3.1.5 on 2021-08-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_auto_20210710_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='imovel',
        ),
        migrations.AddField(
            model_name='imovel',
            name='fotos',
            field=models.ManyToManyField(blank=True, to='imoveis.Foto', verbose_name='fotos'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='img',
            field=models.ImageField(upload_to='fotos/', verbose_name='foto'),
        ),
    ]
