# Generated by Django 3.1.5 on 2021-06-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210618_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='imoveis',
        ),
        migrations.RemoveField(
            model_name='host',
            name='user',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
