# Generated by Django 3.1.5 on 2021-06-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210618_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_host',
            field=models.BooleanField(default=False, help_text='Permite o usuário adicionar imóveis na plataforma.', verbose_name='anfitrião'),
        ),
    ]
